//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///&lt;Modulus&gt;zLizNmLUd4VlIWee1GXgn/KxEwcghPASQ+NUzZhbY2fTGzpW64T6yEOdHlIbhX1DX6yAz2gMZKfnpQL2aFqxh5ACFV9dONSTzuQzkqeXwFEARsMxGP3eTQSWMpwVhEcraSn1zOqMb3CRDeQpgasq0lv4HRFhbwalOifKarjEL/8=&lt;/Modulus&gt;
        ///&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///&lt;P&gt;8+4qCwbxpWFuJje/UURm06Uec+Mk6a7Ye9FGvzVlnh7dYK38GR+bnf8NsoMRW8IlJnipfvqqEs1qnhRAJ4j96Q==&lt;/P&gt;
        ///&lt;Q&gt;1tnh1UK2FxeVSbTXrrvKlSKAWqkjaQwLB+OQeMM5Ii3ogH++91bmO0Ku8GA4qE+r/KfypT4nECQID7i5ykkFpw==&lt;/Q&gt;
        ///&lt;DP&gt;XTEqYtgeTf6xJGy77QJi/ozg24l2OskP8A3+J2LxFb3Y+ey+maKXw38D7qVgZlv/8Xi72MVPYKuWBhr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rsa1 {
            get {
                return ResourceManager.GetString("Rsa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        ///&lt;xsl:stylesheet version=&apos;1.0&apos; xmlns:xsl=&apos;http://www.w3.org/1999/XSL/Transform&apos; xmlns:msxsl=&apos;urn:schemas-microsoft-com:xslt&apos; exclude-result-prefixes=&apos;msxsl&apos;&gt;
        ///  &lt;xsl:output method=&apos;xml&apos; indent=&apos;no&apos; omit-xml-declaration=&apos;yes&apos;/&gt;
        ///  &lt;xsl:param name=&apos;edition&apos;/&gt;
        ///  &lt;xsl:param name=&apos;version&apos;/&gt;
        ///  &lt;xsl:param name=&apos;userspurchased&apos;/&gt;
        ///  
        ///  &lt;xsl:template match=&apos;activationrequest&apos;&gt;
        ///    &lt;data&gt;
        ///      &lt;xsl:text&gt;
        ///&lt;/xsl:text&gt;
        ///      &lt;xsl:apply-templates/&gt;
        ///      &lt;edition&gt;&lt;xsl:valu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Xml1 {
            get {
                return ResourceManager.GetString("Xml1", resourceCulture);
            }
        }
    }
}
